telegram.bot.token=7649691237:AAE2IOIRF6zPcFMLgJ3T7kCpXo4pv-_-kbc
openai.api.key=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
